### ISSUE TITLE
OSMembrane supporting Osmosis 0.45

### ISSUE THREAD

**Issue by samisnunu** [openstreetmap/osmembrane#7]
Hi,
OSMembrane is really an impressive work, easy and very helpful.
However, are you guys planning to upgrade the code to support the latest version of Osmosis 0.45 ?

Sami

**Comment by foxylion** [comment]
Hi Sami,
currently there is no active development. But supporting Osmosis 0.45 should be quite easy. If you want to give it a try, you can modify the XML file (`src/main/resources/de/osmembrane/resources/xml/osmosis-structure.xml`) which defines the supported parameters of Osmosis.

You can find the current XML file (for Osmosis 0.38) [here](https://github.com/openstreetmap/OSMembrane/blob/v1.0.3/src/main/resources/de/osmembrane/resources/xml/osmosis-structure.xml).

When you open a pull request I'll also make a new release supporting Osmosis 0.45.

Regards,
Jakob

**Comment by samisnunu** [comment]
Thanks Jakob,
As per your request, I updated the file you mentioned.
Let's give it a try, if you found issues I can fix it.
The only thing that mattered me is the translation to German for the descriptions of the newly added items marked as '???.' in their tags.

**Comment by foxylion** [comment]
Hi Sami,
this is awesome. I'll have a look at it and try to get it into a new release. Thanks a lot!

**Comment by foxylion** [comment]
Hi Sami,
there where a minor issues with your changes, you removed some spaces in descriptions.
Also I removed all missing German translations, a fallback to the English language will be used.

I've updated your commit, created a pull request (#8) which is already merged.
[A new version should shortly be available](../releases/tag/v1.1.0)

**Comment by foxylion** [comment]
Release is now available. Thanks again for your contribution!
